// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/telemetrypb/telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatteryType int32

const (
	BatteryType_BATTERY_TYPE_UNSPECIFIED BatteryType = 0
	BatteryType_BATTERY_TYPE_VOLTAGE     BatteryType = 1
	BatteryType_BATTERY_TYPE_PERCENT     BatteryType = 2
)

// Enum value maps for BatteryType.
var (
	BatteryType_name = map[int32]string{
		0: "BATTERY_TYPE_UNSPECIFIED",
		1: "BATTERY_TYPE_VOLTAGE",
		2: "BATTERY_TYPE_PERCENT",
	}
	BatteryType_value = map[string]int32{
		"BATTERY_TYPE_UNSPECIFIED": 0,
		"BATTERY_TYPE_VOLTAGE":     1,
		"BATTERY_TYPE_PERCENT":     2,
	}
)

func (x BatteryType) Enum() *BatteryType {
	p := new(BatteryType)
	*p = x
	return p
}

func (x BatteryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatteryType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_telemetrypb_telemetry_proto_enumTypes[0].Descriptor()
}

func (BatteryType) Type() protoreflect.EnumType {
	return &file_internal_telemetrypb_telemetry_proto_enumTypes[0]
}

func (x BatteryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatteryType.Descriptor instead.
func (BatteryType) EnumDescriptor() ([]byte, []int) {
	return file_internal_telemetrypb_telemetry_proto_rawDescGZIP(), []int{0}
}

type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED        SignalType = 0
	SignalType_SIGNAL_TYPE_WIRELESS_VALUE_2G  SignalType = 1
	SignalType_SIGNAL_TYPE_WIRELESS_VALUE_4G  SignalType = 2
	SignalType_SIGNAL_TYPE_WIRELESS_VALUE_868 SignalType = 3
	SignalType_SIGNAL_TYPE_COMET_2G           SignalType = 4
	SignalType_SIGNAL_TYPE_COMET_4G           SignalType = 5
	SignalType_SIGNAL_TYPE_NB_IOT             SignalType = 6
	SignalType_SIGNAL_TYPE_CAT_LTE            SignalType = 7
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNSPECIFIED",
		1: "SIGNAL_TYPE_WIRELESS_VALUE_2G",
		2: "SIGNAL_TYPE_WIRELESS_VALUE_4G",
		3: "SIGNAL_TYPE_WIRELESS_VALUE_868",
		4: "SIGNAL_TYPE_COMET_2G",
		5: "SIGNAL_TYPE_COMET_4G",
		6: "SIGNAL_TYPE_NB_IOT",
		7: "SIGNAL_TYPE_CAT_LTE",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED":        0,
		"SIGNAL_TYPE_WIRELESS_VALUE_2G":  1,
		"SIGNAL_TYPE_WIRELESS_VALUE_4G":  2,
		"SIGNAL_TYPE_WIRELESS_VALUE_868": 3,
		"SIGNAL_TYPE_COMET_2G":           4,
		"SIGNAL_TYPE_COMET_4G":           5,
		"SIGNAL_TYPE_NB_IOT":             6,
		"SIGNAL_TYPE_CAT_LTE":            7,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_telemetrypb_telemetry_proto_enumTypes[1].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_internal_telemetrypb_telemetry_proto_enumTypes[1]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_internal_telemetrypb_telemetry_proto_rawDescGZIP(), []int{1}
}

type BatterySeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatteryType   BatteryType            `protobuf:"varint,1,opt,name=battery_type,json=batteryType,proto3,enum=telemetry.v1.BatteryType" json:"battery_type,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatterySeries) Reset() {
	*x = BatterySeries{}
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatterySeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatterySeries) ProtoMessage() {}

func (x *BatterySeries) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatterySeries.ProtoReflect.Descriptor instead.
func (*BatterySeries) Descriptor() ([]byte, []int) {
	return file_internal_telemetrypb_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *BatterySeries) GetBatteryType() BatteryType {
	if x != nil {
		return x.BatteryType
	}
	return BatteryType_BATTERY_TYPE_UNSPECIFIED
}

func (x *BatterySeries) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SignalSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalType    SignalType             `protobuf:"varint,1,opt,name=signal_type,json=signalType,proto3,enum=telemetry.v1.SignalType" json:"signal_type,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalSeries) Reset() {
	*x = SignalSeries{}
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalSeries) ProtoMessage() {}

func (x *SignalSeries) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalSeries.ProtoReflect.Descriptor instead.
func (*SignalSeries) Descriptor() ([]byte, []int) {
	return file_internal_telemetrypb_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *SignalSeries) GetSignalType() SignalType {
	if x != nil {
		return x.SignalType
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *SignalSeries) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ChannelSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSeries) Reset() {
	*x = ChannelSeries{}
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSeries) ProtoMessage() {}

func (x *ChannelSeries) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSeries.ProtoReflect.Descriptor instead.
func (*ChannelSeries) Descriptor() ([]byte, []int) {
	return file_internal_telemetrypb_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelSeries) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChannelSeries) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type DeploymentSamples struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId        uint64                 `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	DeviceId            *uint64                `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id,omitempty"`
	GatewayDeploymentId *uint64                `protobuf:"varint,3,opt,name=gateway_deployment_id,json=gatewayDeploymentId,proto3,oneof" json:"gateway_deployment_id,omitempty"`
	T0                  uint64                 `protobuf:"varint,4,opt,name=t0,proto3" json:"t0,omitempty"`
	Dt                  []uint32               `protobuf:"varint,5,rep,packed,name=dt,proto3" json:"dt,omitempty"`
	ChannelSeries       []*ChannelSeries       `protobuf:"bytes,6,rep,name=channel_series,json=channelSeries,proto3" json:"channel_series,omitempty"`
	BatterySeries       []*BatterySeries       `protobuf:"bytes,7,rep,name=battery_series,json=batterySeries,proto3" json:"battery_series,omitempty"`
	SignalSeries        []*SignalSeries        `protobuf:"bytes,8,rep,name=signal_series,json=signalSeries,proto3" json:"signal_series,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeploymentSamples) Reset() {
	*x = DeploymentSamples{}
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSamples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSamples) ProtoMessage() {}

func (x *DeploymentSamples) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSamples.ProtoReflect.Descriptor instead.
func (*DeploymentSamples) Descriptor() ([]byte, []int) {
	return file_internal_telemetrypb_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *DeploymentSamples) GetDeploymentId() uint64 {
	if x != nil {
		return x.DeploymentId
	}
	return 0
}

func (x *DeploymentSamples) GetDeviceId() uint64 {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return 0
}

func (x *DeploymentSamples) GetGatewayDeploymentId() uint64 {
	if x != nil && x.GatewayDeploymentId != nil {
		return *x.GatewayDeploymentId
	}
	return 0
}

func (x *DeploymentSamples) GetT0() uint64 {
	if x != nil {
		return x.T0
	}
	return 0
}

func (x *DeploymentSamples) GetDt() []uint32 {
	if x != nil {
		return x.Dt
	}
	return nil
}

func (x *DeploymentSamples) GetChannelSeries() []*ChannelSeries {
	if x != nil {
		return x.ChannelSeries
	}
	return nil
}

func (x *DeploymentSamples) GetBatterySeries() []*BatterySeries {
	if x != nil {
		return x.BatterySeries
	}
	return nil
}

func (x *DeploymentSamples) GetSignalSeries() []*SignalSeries {
	if x != nil {
		return x.SignalSeries
	}
	return nil
}

type Batch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransmissionId     []byte                 `protobuf:"bytes,1,opt,name=transmission_id,json=transmissionId,proto3" json:"transmission_id,omitempty"`
	SourceDeploymentId *uint64                `protobuf:"varint,2,opt,name=source_deployment_id,json=sourceDeploymentId,proto3,oneof" json:"source_deployment_id,omitempty"`
	DeploymentSamples  []*DeploymentSamples   `protobuf:"bytes,3,rep,name=deployment_samples,json=deploymentSamples,proto3" json:"deployment_samples,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetrypb_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_internal_telemetrypb_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *Batch) GetTransmissionId() []byte {
	if x != nil {
		return x.TransmissionId
	}
	return nil
}

func (x *Batch) GetSourceDeploymentId() uint64 {
	if x != nil && x.SourceDeploymentId != nil {
		return *x.SourceDeploymentId
	}
	return 0
}

func (x *Batch) GetDeploymentSamples() []*DeploymentSamples {
	if x != nil {
		return x.DeploymentSamples
	}
	return nil
}

var File_internal_telemetrypb_telemetry_proto protoreflect.FileDescriptor

const file_internal_telemetrypb_telemetry_proto_rawDesc = "" +
	"\n" +
	"$internal/telemetrypb/telemetry.proto\x12\ftelemetry.v1\"i\n" +
	"\rBatterySeries\x12<\n" +
	"\fbattery_type\x18\x01 \x01(\x0e2\x19.telemetry.v1.BatteryTypeR\vbatteryType\x12\x1a\n" +
	"\x06values\x18\x02 \x03(\x02B\x02\x10\x01R\x06values\"e\n" +
	"\fSignalSeries\x129\n" +
	"\vsignal_type\x18\x01 \x01(\x0e2\x18.telemetry.v1.SignalTypeR\n" +
	"signalType\x12\x1a\n" +
	"\x06values\x18\x02 \x03(\x02B\x02\x10\x01R\x06values\"J\n" +
	"\rChannelSeries\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x1a\n" +
	"\x06values\x18\x02 \x03(\x02B\x02\x10\x01R\x06values\"\xa8\x03\n" +
	"\x11DeploymentSamples\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x04R\fdeploymentId\x12 \n" +
	"\tdevice_id\x18\x02 \x01(\x04H\x00R\bdeviceId\x88\x01\x01\x127\n" +
	"\x15gateway_deployment_id\x18\x03 \x01(\x04H\x01R\x13gatewayDeploymentId\x88\x01\x01\x12\x0e\n" +
	"\x02t0\x18\x04 \x01(\x04R\x02t0\x12\x12\n" +
	"\x02dt\x18\x05 \x03(\rB\x02\x10\x01R\x02dt\x12B\n" +
	"\x0echannel_series\x18\x06 \x03(\v2\x1b.telemetry.v1.ChannelSeriesR\rchannelSeries\x12B\n" +
	"\x0ebattery_series\x18\a \x03(\v2\x1b.telemetry.v1.BatterySeriesR\rbatterySeries\x12?\n" +
	"\rsignal_series\x18\b \x03(\v2\x1a.telemetry.v1.SignalSeriesR\fsignalSeriesB\f\n" +
	"\n" +
	"_device_idB\x18\n" +
	"\x16_gateway_deployment_id\"\xd0\x01\n" +
	"\x05Batch\x12'\n" +
	"\x0ftransmission_id\x18\x01 \x01(\fR\x0etransmissionId\x125\n" +
	"\x14source_deployment_id\x18\x02 \x01(\x04H\x00R\x12sourceDeploymentId\x88\x01\x01\x12N\n" +
	"\x12deployment_samples\x18\x03 \x03(\v2\x1f.telemetry.v1.DeploymentSamplesR\x11deploymentSamplesB\x17\n" +
	"\x15_source_deployment_id*_\n" +
	"\vBatteryType\x12\x1c\n" +
	"\x18BATTERY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BATTERY_TYPE_VOLTAGE\x10\x01\x12\x18\n" +
	"\x14BATTERY_TYPE_PERCENT\x10\x02*\xf8\x01\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSIGNAL_TYPE_WIRELESS_VALUE_2G\x10\x01\x12!\n" +
	"\x1dSIGNAL_TYPE_WIRELESS_VALUE_4G\x10\x02\x12\"\n" +
	"\x1eSIGNAL_TYPE_WIRELESS_VALUE_868\x10\x03\x12\x18\n" +
	"\x14SIGNAL_TYPE_COMET_2G\x10\x04\x12\x18\n" +
	"\x14SIGNAL_TYPE_COMET_4G\x10\x05\x12\x16\n" +
	"\x12SIGNAL_TYPE_NB_IOT\x10\x06\x12\x17\n" +
	"\x13SIGNAL_TYPE_CAT_LTE\x10\aB1Z/device-handler/internal/telemetrypb;telemetrypbb\x06proto3"

var (
	file_internal_telemetrypb_telemetry_proto_rawDescOnce sync.Once
	file_internal_telemetrypb_telemetry_proto_rawDescData []byte
)

func file_internal_telemetrypb_telemetry_proto_rawDescGZIP() []byte {
	file_internal_telemetrypb_telemetry_proto_rawDescOnce.Do(func() {
		file_internal_telemetrypb_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_telemetrypb_telemetry_proto_rawDesc), len(file_internal_telemetrypb_telemetry_proto_rawDesc)))
	})
	return file_internal_telemetrypb_telemetry_proto_rawDescData
}

var file_internal_telemetrypb_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_telemetrypb_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_telemetrypb_telemetry_proto_goTypes = []any{
	(BatteryType)(0),          // 0: telemetry.v1.BatteryType
	(SignalType)(0),           // 1: telemetry.v1.SignalType
	(*BatterySeries)(nil),     // 2: telemetry.v1.BatterySeries
	(*SignalSeries)(nil),      // 3: telemetry.v1.SignalSeries
	(*ChannelSeries)(nil),     // 4: telemetry.v1.ChannelSeries
	(*DeploymentSamples)(nil), // 5: telemetry.v1.DeploymentSamples
	(*Batch)(nil),             // 6: telemetry.v1.Batch
}
var file_internal_telemetrypb_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.BatterySeries.battery_type:type_name -> telemetry.v1.BatteryType
	1, // 1: telemetry.v1.SignalSeries.signal_type:type_name -> telemetry.v1.SignalType
	4, // 2: telemetry.v1.DeploymentSamples.channel_series:type_name -> telemetry.v1.ChannelSeries
	2, // 3: telemetry.v1.DeploymentSamples.battery_series:type_name -> telemetry.v1.BatterySeries
	3, // 4: telemetry.v1.DeploymentSamples.signal_series:type_name -> telemetry.v1.SignalSeries
	5, // 5: telemetry.v1.Batch.deployment_samples:type_name -> telemetry.v1.DeploymentSamples
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_telemetrypb_telemetry_proto_init() }
func file_internal_telemetrypb_telemetry_proto_init() {
	if File_internal_telemetrypb_telemetry_proto != nil {
		return
	}
	file_internal_telemetrypb_telemetry_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_telemetrypb_telemetry_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_telemetrypb_telemetry_proto_rawDesc), len(file_internal_telemetrypb_telemetry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_telemetrypb_telemetry_proto_goTypes,
		DependencyIndexes: file_internal_telemetrypb_telemetry_proto_depIdxs,
		EnumInfos:         file_internal_telemetrypb_telemetry_proto_enumTypes,
		MessageInfos:      file_internal_telemetrypb_telemetry_proto_msgTypes,
	}.Build()
	File_internal_telemetrypb_telemetry_proto = out.File
	file_internal_telemetrypb_telemetry_proto_goTypes = nil
	file_internal_telemetrypb_telemetry_proto_depIdxs = nil
}
